#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later

from os import scandir
from sys import argv

def print_no_lf(*args):
	print(*args, end = '')

def sort_deps(item):
	return not isinstance(item, list)

def find_deps(dir):
	ents = scandir(dir)
	deps = [ dir ]

	for ent in ents:
		item = ent.path

		if item.endswith('_entry.c'):
			continue

		if not '.' in ent.name:
			item = find_deps(ent.path)

		deps.append(item)

	return deps

def print_headers(deps):
	first = 1

	for item in deps:
		if isinstance(item, list):
			print_headers(item)
			continue

		if first:
			print_no_lf(f"include/{item}/d.h: |")
		else:
			print_no_lf(f" {item}")

		first = 0

	print('\n')

def print_object_deps(deps):
	first = 1

	for item in deps:
		if isinstance(item, list):
			print_object_deps(item)
			continue

		if first:
			header = item

			print_no_lf(f"build/{item}.o")
		else:
			print_no_lf(f" build/{item[0:-2]}.o")

		first = 0

	print(f": include/{header}/d.h\n")

def object_path(item):
	if item.endswith('.c'):
		item = item[0:-2]

	return f"build/{item}.o"

def collect_objects(deps):
	objects = []

	for item in deps:
		if isinstance(item, list):
			objects += collect_objects(item)
			continue

		objects.append(object_path(item))

	return objects

def print_binary_deps(deps):
	root = None
	seen = set()

	for item in deps:
		if isinstance(item, list):
			print_binary_deps(item)
			continue

		if root is None:
			root = item

	print_no_lf(f"build/{root}/entry:")
	print_no_lf(f" build/{root}_entry.o")

	for obj in collect_objects(deps):
		if obj in seen:
			continue

		print_no_lf(f" {obj}")
		seen.add(obj)

	print('\n')

def print_command_object_y(deps):
	first = 1

	for item in deps:
		if isinstance(item, list):
			print_command_object_y(item)
			continue

		if first:
			print_no_lf('cmd-obj-y +=')
			print_no_lf(f" build/{item}.o")
			print_no_lf(f" build/{item}_entry.o")
		else:
			print_no_lf(f" build/{item[0:-2]}.o")

		first = 0

	print('\n')

main = argv[1]
init = main.split('.')[0]
deps = find_deps(init)

deps.sort(key = sort_deps)

print(f"# Generated by {argv[0]}\n")

print_headers(deps)

print_object_deps(deps)

print_binary_deps(deps)

print_command_object_y(deps)
