#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

cat <<EOF
/* Generated by $0 */

#ifndef COMMAND_H
#define COMMAND_H

struct command {
	const char *name;
	int (*routine)(int argc, const char **argv);
};

$(sed 's/\(.*\)\.c/int cmd_\1(int argc, const char **argv);/')

#endif /* COMMAND_H */
EOF
