#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

cat <<EOF
/* Generated by $0 */

#ifndef BUILD_H
#define BUILD_H

EOF

while read file; do
	printf '#define '
	printf '%s ' $file | sed $* -e s,/,_,g | tr [:lower:] [:upper:]
	cat $file | sed 's/^.*$/"&"/'
done

cat <<EOF

#endif /* BUILD_H */
EOF
