#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

trap 'rm -f .tmp-$$' EXIT

prefix=$(printf '%s' $1 | sed -e 's|^main/||' -e 's|/$|_|')
name=$(basename $1)
class=$(printf '%s' $name | tr [:lower:] [:upper:])

match='s|.*/\([^/]*\).c'
opt_replace="\tPA_OPT_CMD(\"\1\", v, cmd_$prefix\1, cmd_$prefix\1_help)"

cat >.tmp-$$

cat <<EOF
/* Generated by $0 */

#ifndef CMD_${class}_D_H
#define CMD_${class}_D_H

#include "parse_argv.h"

EOF

sed $match"|int cmd_$prefix\1(int argc, const char **argv);|" .tmp-$$

printf 'int cmd_%s(int argc, const char **argv);\n' $name

printf '\n'

sed $match"|extern const char *cmd_$prefix\1_help;|" .tmp-$$

printf '\n'

cat <<EOF
#define CMD_${class}_CMDS(v) \\
EOF

sed -e \$!$match"|$opt_replace, \\\\|" -e \$$match"|$opt_replace|" .tmp-$$

cat <<EOF

#endif /* CMD_${class}_D_H */
EOF
