#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

cat <<EOF
/* Generated by $0 */

#ifndef FEATURES_H
#define FEATURES_H

EOF

awk -F= '{ print "#define " $1 }'

cat <<EOF

#endif /* FEATURES_H */
EOF
