#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later

from re import search
from subprocess import run
from sys import argv, stdout
from os.path import exists

def print_range(begin, end):
	print(f'\t{{ {hex(begin)}, {hex(end)} }},')

file = 'EastAsianWidth.txt'
url = f"https://www.unicode.org/Public/UCD/latest/ucd/{file}"

if not exists(file):
	run([ 'curl', '-fsSLO', url ], check=True)

stream = open(file, 'r')
entry = [ 0, 0 ]

print(f'''\
/* Generated by {argv[0]} */

#include "unicode.h"

#include "calc.h"

static const wchar_t table[][2] = {{\
''')

for line in stream:
	if not search(r';\s*[WF]\s', line):
		continue

	cols = line.split()
	vals = cols[0].split('..')

	begin = int(vals[0], 16)
	end = int(vals[1] if len(vals) == 2 else vals[0], 16)

	if begin > 0xffff:
		break

	if entry[1] + 1 == begin:
		entry[1] = end
	else:
		if entry[0]:
			print_range(entry[0], entry[1])

		entry[0] = begin
		entry[1] = end

print_range(entry[0], entry[1])

print('''\
};

int uc_iswide(wchar_t c)
{
	if (c < table[0][0])
		return 0;

	size_t l = 0;
	size_t r = sizeof_array(table);

	while (l < r) {
		size_t m = (l + r) >> 1;

		if (c < table[m][0])
			r = m;
		else if (c > table[m][1])
			l = m + 1;
		else
			return 1;
	}

	return 0;
}\
''')
