#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

cat <<EOF
/* Generated by $0 */

#include <stddef.h>

#include "commands.h"

struct command commands[] = {
$(sed 's/\(.*\)\.c/\t{ .name = "\1", .routine = cmd_\1 },/')
	{ 0 },
};
EOF
