# SPDX-License-Identifier: GPL-3.0-or-later

bootstrap: build/probe/cc/program \
	   build/probe/cc/id \
	   build/probe/cc/version \
	   build/probe/cc/name \
	   build/probe/cc/features \
	   build/probe/ld/program \
	   build/probe/ld/id \
	   build/probe/ld/version \
	   build/probe/ld/name \
	   build/probe/ld/features \
	   build/probe/repo/name \
	   build/probe/repo/version \
	   build/probe/host/id \
	   build/probe/host/arch \
	   build/probe/host/name \
	   build/probe/utf8/locale

include/generated/build.h: build/probe/repo/name build/probe/repo/version \
		     build/probe/host/id build/probe/host/arch \
		     build/probe/host/name
	mkdir -p $(@D)
	printf '%s\n' $^ | ./scripts/gen-build_h.sh -e s,[^/]\\+/repo,repo, >$@

include/generated/features.h: build/probe/cc/features \
			build/probe/ld/features
	mkdir -p $(@D)
	cat $^ | ./scripts/gen-features_h.sh >$@

build/probe/repo/name:
	mkdir -p $(@D)
	printf '%s\n' $(name) >$@

build/probe/repo/version:
	mkdir -p $(@D)
	printf '%s\n' $(version) >$@

build/probe/host/id:
	mkdir -p $(@D)
	python3 -c 'import sys; print(sys.platform)' >$@

build/probe/host/arch:
	mkdir -p $(@D)
	python3 -c 'import platform; print(platform.machine())' >$@

build/probe/host/name:
	mkdir -p $(@D)
	python3 -c 'import platform; print(platform.system())' >$@

build/probe/cc/program: build/probe/cc/.dump
	cut -f1 $< >$@

build/probe/cc/id: build/probe/cc/.dump
	cut -f2 $< >$@

build/probe/cc/version: build/probe/cc/.dump
	cut -f3 $< >$@

build/probe/cc/name: build/probe/cc/.dump
	cut -f4 $< >$@

build/probe/cc/.dump: build/probe/tools
	mkdir -p $(@D)
	sed -n 1p $< >$@

build/probe/cc/features:

build/probe/ld/program: build/probe/ld/.dump
	cut -f1 $< >$@

build/probe/ld/id: build/probe/ld/.dump
	cut -f2 $< >$@

build/probe/ld/version: build/probe/ld/.dump
	cut -f3 $< >$@

build/probe/ld/name: build/probe/ld/.dump
	cut -f4 $< >$@

build/probe/ld/.dump: build/probe/tools
	mkdir -p $(@D)
	sed -n 2p $< >$@

build/probe/ld/features: build/probe/cc/program build/probe/ld/id

build/probe/tools:
	mkdir -p $(@D)
	trap 'rm -f .tmp-$$$$' EXIT && \
	./scripts/probe-tools.sh >.tmp-$$$$ && \
	mv .tmp-$$$$ $@

build/probe/%/features: build/probe/%/program
	trap 'rm -f .tmp-$$$$' EXIT && \
	./scripts/probe-$*-features.sh $$(cat $^) | \
	sort >.tmp-$$$$ && $(call mv_stale,.tmp-$$$$,$(@),$?)

build/probe/utf8/locale:
	mkdir -p $(@D)
	./scripts/probe-utf8-locale.sh >$@
