# SPDX-License-Identifier: GPL-3.0-or-later

$(objtree)/cc.info: $(objtree)/toolchain.info
	head -1 $< >$@

$(objtree)/ld.info: $(objtree)/toolchain.info
	tail -1 $< >$@

$(objtree)/toolchain.info:
	mkdir -p $(@D)
	trap 'rm -f .tmp-$$$$' EXIT && \
	scripts/find-toolchain.py >.tmp-$$$$ && \
	mv .tmp-$$$$ $@

$(objtree)/repo.info:
	mkdir -p $(@D)
	printf '%s\t%s\n' $(name) $(version) >$@
