# SPDX-License-Identifier: GPL-3.0-or-later

$(objtree)/unitest/strbuf_alloc.run: $(objtree)/unitest/log.run

$(objtree)/unitest/log.run: $(objtree)/unitest/strbuf_prealloc.run

$(objtree)/unitest/%.run: $(objtree)/unitest/%
	printf '%s\n' $(patsubst %.run,%.pass,$(filter %.run,$^)) >$<.deps
	rm -f $<.pass
	printf '\n== %s\n' $<
	time -p $< $<.deps 2>$<.err | ./tapview/tapview && touch $<.pass || true
	printf '\n'
	cat $<.err

